UV ?= uv
PYTHON ?= $(UV) run python
-include .env

# Marker generated by the datasets target after a successful download.
DATASET_STAMP := $(DATASET_ROOT)/.downloaded

.PHONY: setup sync hooks datasets format lint optuna_dashboard

setup: sync hooks datasets

sync:
	$(UV) sync

hooks:
	git config core.hooksPath ./.git-hooks

datasets: $(DATASET_STAMP)

$(DATASET_STAMP): dataset.sh .env
	bash dataset.sh
	touch "$@"

format:
	$(UV) run ruff format .

lint: format
	$(UV) run ruff check --fix .

optuna_dashboard:
	@storage_url="$$( $(PYTHON) -c 'from peincfedmdrs.utils.optuna import build_storage_name; print(build_storage_name())')"; \
	$(UV) run optuna-dashboard "$$storage_url" --host 0.0.0.0
