UV ?= uv
PYTHON ?= $(UV) run python
-include .env

# Marker generated by the datasets target after a successful download.
DATASET_STAMP := $(DATASET_ROOT)/.downloaded

.PHONY: setup sync hooks datasets format lint optuna_dashboard scripts \
	visualize visualize-datasets cudb-anomaly-scores entity-info study \
	sddb-concat-constants sddb-concat-utils \
	sddb-concat-visualize sddb-concat-score \
	ltafdb-concat ltafdb-concat-constants ltafdb-concat-utils \
	ltafdb-concat-visualize ltafdb-concat-score

setup: sync hooks datasets

sync:
	$(UV) sync

hooks:
	git config core.hooksPath ./.git-hooks

datasets: $(DATASET_STAMP)

$(DATASET_STAMP): dataset.sh .env
	bash dataset.sh
	touch "$@"

format:
	$(UV) run ruff format .

lint: format
	$(UV) run ruff check --fix .

optuna_dashboard:
	@storage_url="$$( $(PYTHON) -c 'from peincfedmdrs.utils.optuna import build_storage_name; print(build_storage_name())')"; \
	$(UV) run optuna-dashboard "$$storage_url" --host 0.0.0.0

scripts:
	@printf '%s\n' \
		'visualize' \
		'visualize-datasets' \
		'cudb-anomaly-scores' \
		'entity-info' \
		'study' \
		'sddb-concat' \
		'sddb-concat-visualize' \
			'sddb-concat-score' \
			'ltafdb-concat' \
			'ltafdb-concat-visualize' \
			'ltafdb-concat-score'

visualize:
	$(PYTHON) -m ecg_visualization.scripts.visualize

visualize-datasets:
	$(PYTHON) -m ecg_visualization.scripts.visualize_datasets

cudb-anomaly-scores:
	$(PYTHON) -m ecg_visualization.scripts.cudb_anomaly_scores

entity-info:
	$(PYTHON) -m ecg_visualization.scripts.entity_info

study:
	$(PYTHON) -m ecg_visualization.scripts.study

sddb-concat:
	$(PYTHON) -m ecg_visualization.scripts.sddb_concat

sddb-concat-visualize:
	$(PYTHON) -m ecg_visualization.scripts.sddb_concat.visualize

sddb-concat-score:
	$(PYTHON) -m ecg_visualization.scripts.sddb_concat.score

ltafdb-concat:
	$(PYTHON) -m ecg_visualization.scripts.ltafdb_concat

ltafdb-concat-visualize:
	$(PYTHON) -m ecg_visualization.scripts.ltafdb_concat.visualize

ltafdb-concat-score:
	$(PYTHON) -m ecg_visualization.scripts.ltafdb_concat.score
